export const LOAD_FACTS_REQUEST = 'LOAD_FACTS_REQUEST';
export const LOAD_FACTS_SUCCESS = 'LOAD_FACTS_SUCCESS';
export const LOAD_FACTS_FAIL = 'LOAD_FACTS_FAIL';
export const FACTS_CLEAR = 'FACTS_CLEAR';
